services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: compute-allocator-backend
    env_file:
      - ./backend/.env
    environment:
      - KUBECONFIG=/root/.kube/config
    ports:
      - "8000:8000"
    volumes:
      - ${USERPROFILE}/.kube:/root/.kube:ro
      - ${USERPROFILE}/.minikube:/root/.minikube:ro

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: compute-allocator-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
